# -*- coding: utf-8 -*-
"""without_aug_swin_med3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bqtn-WUA-XQVMumTexUD2MH1xuHbgY3W
"""

# -*- coding: utf-8 -*-
"""swin_med3_no_aug.ipynb

Modified version of swin_med3_aug.py with data augmentation removed
"""

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from transformers import SwinModel, SwinConfig, AutoImageProcessor
from PIL import Image, ImageOps
import os
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix
import cv2
import random
import pandas as pd


class FetalMRIHybridDataset(Dataset):
    def __init__(self, data_dir, swin_processor, is_train=True):
        self.data_dir = data_dir
        self.swin_processor = swin_processor
        self.is_train = is_train
        self.classes = sorted(os.listdir(data_dir))
        self.class_to_idx = {cls: idx for idx, cls in enumerate(self.classes)}

        self.image_paths = []
        self.labels = []

        for class_name in self.classes:
            class_dir = os.path.join(data_dir, class_name)
            for img_name in os.listdir(class_dir):
                if img_name.endswith(('.jpg', '.png', '.jpeg')):
                    self.image_paths.append(os.path.join(class_dir, img_name))
                    self.labels.append(self.class_to_idx[class_name])

        # Simple transforms for both training and validation/testing
        # No data augmentation is applied
        self.cnn_transforms = transforms.Compose([
            transforms.Resize(224),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image_path = self.image_paths[idx]
        image = Image.open(image_path).convert('RGB')

        # Process for Swin Transformer
        swin_processed = self.swin_processor(images=image, return_tensors="pt")
        swin_pixels = swin_processed.pixel_values.squeeze()

        # Process for CNN - no augmentations
        cnn_pixels = self.cnn_transforms(image)

        label = self.labels[idx]
        return swin_pixels, cnn_pixels, label


class MultiHeadCrossAttention(nn.Module):
    def __init__(self, query_dim, key_dim, num_heads=8, dropout=0.1):
        super().__init__()
        self.num_heads = num_heads
        self.head_dim = query_dim // num_heads
        self.scale = self.head_dim ** -0.5

        self.q_proj = nn.Linear(query_dim, query_dim)
        self.k_proj = nn.Linear(key_dim, query_dim)
        self.v_proj = nn.Linear(key_dim, query_dim)
        self.out_proj = nn.Linear(query_dim, query_dim)

        self.dropout = nn.Dropout(dropout)

    def forward(self, query, key, value):
        batch_size = query.shape[0]

        # Project and reshape for multi-head attention
        q = self.q_proj(query).view(batch_size, -1, self.num_heads, self.head_dim).transpose(1, 2)
        k = self.k_proj(key).view(batch_size, -1, self.num_heads, self.head_dim).transpose(1, 2)
        v = self.v_proj(value).view(batch_size, -1, self.num_heads, self.head_dim).transpose(1, 2)

        # Compute attention scores
        scores = torch.matmul(q, k.transpose(-2, -1)) * self.scale
        attn_weights = torch.softmax(scores, dim=-1)
        attn_weights = self.dropout(attn_weights)

        # Apply attention to values
        out = torch.matmul(attn_weights, v)
        out = out.transpose(1, 2).contiguous().view(batch_size, -1, query.shape[-1])

        return self.out_proj(out)


class Med3DFeatureExtractor(nn.Module):
    def __init__(self):
        super().__init__()
        # Define Med3D architecture - more suitable for medical imaging
        self.features = nn.Sequential(
            # Initial layer
            nn.Conv2d(3, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),

            # First block - specialized for medical imaging
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.Conv2d(128, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),

            # Second block with dilated convolutions
            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),
            nn.Conv2d(256, 256, kernel_size=3, padding=1, dilation=2),  # Dilated conv for larger receptive field
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),
            nn.Conv2d(256, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),

            # Third block
            nn.Conv2d(256, 512, kernel_size=3, padding=1),
            nn.BatchNorm2d(512),
            nn.ReLU(inplace=True),
            nn.Conv2d(512, 512, kernel_size=3, padding=2, dilation=2),  # Dilated conv
            nn.BatchNorm2d(512),
            nn.ReLU(inplace=True),
            nn.Conv2d(512, 512, kernel_size=3, padding=1),
            nn.BatchNorm2d(512),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),

            # Fourth block
            nn.Conv2d(512, 512, kernel_size=3, padding=1),
            nn.BatchNorm2d(512),
            nn.ReLU(inplace=True),
            nn.Conv2d(512, 512, kernel_size=3, padding=1),
            nn.BatchNorm2d(512),
            nn.ReLU(inplace=True),
        )
        self.feature_dim = 512

        # Only freeze the initial layers, allow more layers to be fine-tuned
        for i, param in enumerate(self.features.parameters()):
            if i < 8:  # Only freeze the first few layers
                param.requires_grad = False

    def forward(self, x):
        features = self.features(x)
        return features


class FeatureFusionTransformer(nn.Module):
    def __init__(self, swin_dim, cnn_dim, num_heads=8, dropout=0.1):
        super().__init__()

        self.cnn_projection = nn.Sequential(
            nn.Linear(cnn_dim, swin_dim),
            nn.LayerNorm(swin_dim),
            nn.ReLU()
        )

        self.cross_attention = MultiHeadCrossAttention(
            query_dim=swin_dim,
            key_dim=swin_dim,
            num_heads=num_heads,
            dropout=dropout
        )

        self.fusion_layer = nn.Sequential(
            nn.Linear(swin_dim * 2, swin_dim),
            nn.LayerNorm(swin_dim),
            nn.ReLU(),
            nn.Dropout(dropout)
        )

    def forward(self, swin_features, cnn_features):
        # Project CNN features to Swin dimension
        cnn_features = self.cnn_projection(cnn_features)

        # Cross attention between Swin and CNN features
        attended_features = self.cross_attention(swin_features, cnn_features, cnn_features)

        # Concatenate and fuse features
        fused_features = torch.cat([swin_features, attended_features], dim=-1)
        fused_features = self.fusion_layer(fused_features)

        return fused_features


class HybridCNNSwin(nn.Module):
    def __init__(self, num_classes, swin_model_name="microsoft/swin-base-patch4-window7-224-in22k"):
        super().__init__()

        # Swin Transformer Component
        self.swin = SwinModel.from_pretrained(swin_model_name)
        self.swin_dim = self.swin.config.hidden_size

        # Unfreeze more layers in Swin for better fine-tuning
        # Only freeze the initial embedding layers and first few transformer blocks
        for i, param in enumerate(self.swin.parameters()):
            # Keep early layers frozen, unfreeze more layers
            if i >= len(list(self.swin.parameters())) // 3:  # Unfreeze 2/3 of the Swin model
                param.requires_grad = True
            else:
                param.requires_grad = False

        # Med3D Component
        self.cnn = Med3DFeatureExtractor()
        self.cnn_dim = self.cnn.feature_dim

        # Feature Fusion
        self.fusion_transformer = FeatureFusionTransformer(
            swin_dim=self.swin_dim,
            cnn_dim=self.cnn_dim
        )

        # Classification Head
        self.classifier = nn.Sequential(
            nn.Linear(self.swin_dim, self.swin_dim // 2),
            nn.LayerNorm(self.swin_dim // 2),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(self.swin_dim // 2, num_classes)
        )

    def forward(self, swin_x, cnn_x):
        # Get Swin Transformer features
        swin_output = self.swin(swin_x)
        # Use pooled output for Swin
        swin_features = swin_output.pooler_output

        # Get CNN features
        batch_size = cnn_x.size(0)
        cnn_features = self.cnn(cnn_x)
        cnn_features = cnn_features.view(batch_size, self.cnn_dim, -1).mean(dim=2)

        # Fuse features using transformer
        fused_features = self.fusion_transformer(
            swin_features.unsqueeze(1),
            cnn_features.unsqueeze(1)
        ).squeeze(1)

        # Classification
        output = self.classifier(fused_features)
        return output


def train_model(model, train_loader, criterion, optimizer, device, scheduler=None):
    model.train()
    running_loss = 0.0
    all_preds = []
    all_labels = []

    for swin_images, cnn_images, labels in tqdm(train_loader, desc="Training"):
        swin_images = swin_images.to(device)
        cnn_images = cnn_images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()
        outputs = model(swin_images, cnn_images)
        loss = criterion(outputs, labels)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        if scheduler is not None:
            scheduler.step()

        running_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    epoch_loss = running_loss / len(train_loader)
    accuracy = accuracy_score(all_labels, all_preds)
    precision, recall, f1, _ = precision_recall_fscore_support(all_labels, all_preds, average='weighted')

    return epoch_loss, accuracy, precision, recall, f1


def evaluate_model(model, val_loader, criterion, device):
    model.eval()
    running_loss = 0.0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for swin_images, cnn_images, labels in tqdm(val_loader, desc="Evaluating"):
            swin_images = swin_images.to(device)
            cnn_images = cnn_images.to(device)
            labels = labels.to(device)

            outputs = model(swin_images, cnn_images)
            loss = criterion(outputs, labels)

            running_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    val_loss = running_loss / len(val_loader)
    accuracy = accuracy_score(all_labels, all_preds)
    precision, recall, f1, _ = precision_recall_fscore_support(all_labels, all_preds, average='weighted')

    return val_loss, accuracy, precision, recall, f1, all_preds, all_labels


def plot_metrics(metrics_history, fold, save_dir='./plots_no_aug'):
    """
    Plot training and validation metrics (loss and accuracy) per epoch

    Args:
        metrics_history: Dictionary with metrics history
        fold: Current fold number
        save_dir: Directory to save plots
    """
    os.makedirs(save_dir, exist_ok=True)

    # Create a figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

    # Plot loss curves
    ax1.plot(metrics_history['train_loss'], 'b-', label='Training Loss')
    ax1.plot(metrics_history['val_loss'], 'r-', label='Validation Loss')
    ax1.set_title(f'Fold {fold}: Loss Curves (No Augmentation)')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Loss')
    ax1.legend()
    ax1.grid(True)

    # Plot accuracy curves
    ax2.plot(metrics_history['train_acc'], 'b-', label='Training Accuracy')
    ax2.plot(metrics_history['val_acc'], 'r-', label='Validation Accuracy')
    ax2.set_title(f'Fold {fold}: Accuracy Curves (No Augmentation)')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Accuracy')
    ax2.legend()
    ax2.grid(True)

    plt.tight_layout()
    plt.savefig(f'{save_dir}/metrics_fold_{fold}.png')
    plt.close()


def plot_fold_comparison(all_folds_metrics, save_dir='./plots_no_aug'):
    """
    Plot comparison of metrics across all folds

    Args:
        all_folds_metrics: List of dictionaries with metrics for each fold
        save_dir: Directory to save plots
    """
    os.makedirs(save_dir, exist_ok=True)

    # Extract metrics across folds
    folds = list(range(1, len(all_folds_metrics) + 1))
    best_val_acc = [metrics['best_val_acc'] for metrics in all_folds_metrics]
    best_val_loss = [metrics['best_val_loss'] for metrics in all_folds_metrics]

    # Create a figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

    # Plot best validation accuracy per fold
    ax1.bar(folds, best_val_acc, color='green')
    ax1.set_title('Best Validation Accuracy per Fold (No Augmentation)')
    ax1.set_xlabel('Fold')
    ax1.set_ylabel('Accuracy')
    ax1.set_ylim([0, 1])
    for i, v in enumerate(best_val_acc):
        ax1.text(i + 1, v + 0.02, f'{v:.4f}', ha='center')

    # Plot best validation loss per fold
    ax2.bar(folds, best_val_loss, color='red')
    ax2.set_title('Best Validation Loss per Fold (No Augmentation)')
    ax2.set_xlabel('Fold')
    ax2.set_ylabel('Loss')
    for i, v in enumerate(best_val_loss):
        ax2.text(i + 1, v + 0.02, f'{v:.4f}', ha='center')

    plt.tight_layout()
    plt.savefig(f'{save_dir}/fold_comparison.png')
    plt.close()


def plot_average_metrics_across_epochs(all_folds_metrics, save_dir='./plots_no_aug'):
    """
    Plot average metrics across all folds for each epoch

    Args:
        all_folds_metrics: List of dictionaries with metrics for each fold
        save_dir: Directory to save plots
    """
    os.makedirs(save_dir, exist_ok=True)

    # Find the maximum number of epochs across all folds
    max_epochs = max([len(metrics['train_loss']) for metrics in all_folds_metrics])

    # Initialize arrays to store average metrics
    avg_train_loss = np.zeros(max_epochs)
    avg_val_loss = np.zeros(max_epochs)
    avg_train_acc = np.zeros(max_epochs)
    avg_val_acc = np.zeros(max_epochs)

    # Count how many folds have data for each epoch
    counts = np.zeros(max_epochs)

    # Sum up metrics from all folds
    for metrics in all_folds_metrics:
        for e in range(len(metrics['train_loss'])):
            avg_train_loss[e] += metrics['train_loss'][e]
            avg_val_loss[e] += metrics['val_loss'][e]
            avg_train_acc[e] += metrics['train_acc'][e]
            avg_val_acc[e] += metrics['val_acc'][e]
            counts[e] += 1

    # Calculate averages
    for e in range(max_epochs):
        if counts[e] > 0:
            avg_train_loss[e] /= counts[e]
            avg_val_loss[e] /= counts[e]
            avg_train_acc[e] /= counts[e]
            avg_val_acc[e] /= counts[e]

    # Create a figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

    # Plot average loss curves
    epochs = list(range(1, max_epochs + 1))
    ax1.plot(epochs, avg_train_loss, 'b-', label='Avg Training Loss')
    ax1.plot(epochs, avg_val_loss, 'r-', label='Avg Validation Loss')
    ax1.set_title('Average Loss Across Folds (No Augmentation)')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Loss')
    ax1.legend()
    ax1.grid(True)

    # Plot average accuracy curves
    ax2.plot(epochs, avg_train_acc, 'b-', label='Avg Training Accuracy')
    ax2.plot(epochs, avg_val_acc, 'r-', label='Avg Validation Accuracy')
    ax2.set_title('Average Accuracy Across Folds (No Augmentation)')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Accuracy')
    ax2.legend()
    ax2.grid(True)

    plt.tight_layout()
    plt.savefig(f'{save_dir}/average_metrics.png')
    plt.close()


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # Initialize Swin Transformer processor
    swin_processor = AutoImageProcessor.from_pretrained("microsoft/swin-base-patch4-window7-224-in22k")

    # Dataset setup
    train_dir = "/home/rifat/Dr.Rifat_sir_student_SUHA/FetalMRI_Dataset/"  # Update with your path
    dataset = FetalMRIHybridDataset(train_dir, swin_processor, is_train=True)

    # K-fold cross-validation setup
    k_folds = 2
    kfold = KFold(n_splits=k_folds, shuffle=True, random_state=42)

    # Store results
    all_results = []
    all_folds_metrics = []

    # Create directories for saving plots
    plots_dir = './plots_no_aug'
    os.makedirs(plots_dir, exist_ok=True)
    models_dir = './models_no_aug'
    os.makedirs(models_dir, exist_ok=True)

    for fold, (train_ids, val_ids) in enumerate(kfold.split(dataset)):
        print(f'\nFold {fold+1}/{k_folds}')

        # Create data loaders
        train_loader = DataLoader(dataset, batch_size=8, sampler=torch.utils.data.SubsetRandomSampler(train_ids))

        # Create a separate validation dataset
        val_dataset = FetalMRIHybridDataset(train_dir, swin_processor, is_train=False)
        val_loader = DataLoader(val_dataset, batch_size=8, sampler=torch.utils.data.SubsetRandomSampler(val_ids))

        # Initialize model
        model = HybridCNNSwin(num_classes=len(dataset.classes))
        model = model.to(device)

        # Training setup
        criterion = nn.CrossEntropyLoss()
        optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=0.01)

        # Learning rate scheduler
        num_training_steps = len(train_loader) * 10  # 10 epochs
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_training_steps)

        # Training
        epochs = 10
        best_val_acc = 0.0
        best_val_loss = float('inf')
        patience = 3
        patience_counter = 0

        # Metrics history
        metrics_history = {
            'train_loss': [],
            'train_acc': [],
            'val_loss': [],
            'val_acc': [],
            'train_precision': [],
            'train_recall': [],
            'train_f1': [],
            'val_precision': [],
            'val_recall': [],
            'val_f1': []
        }

        for epoch in range(epochs):
            print(f'Epoch {epoch+1}/{epochs}')

            # Train the model
            train_loss, train_acc, train_precision, train_recall, train_f1 = train_model(
                model, train_loader, criterion, optimizer, device, scheduler
            )

            # Evaluate the model
            val_loss, val_acc, val_precision, val_recall, val_f1, val_preds, val_labels = evaluate_model(
                model, val_loader, criterion, device
            )

            # Update metrics history
            metrics_history['train_loss'].append(train_loss)
            metrics_history['train_acc'].append(train_acc)
            metrics_history['val_loss'].append(val_loss)
            metrics_history['val_acc'].append(val_acc)
            metrics_history['train_precision'].append(train_precision)
            metrics_history['train_recall'].append(train_recall)
            metrics_history['train_f1'].append(train_f1)
            metrics_history['val_precision'].append(val_precision)
            metrics_history['val_recall'].append(val_recall)
            metrics_history['val_f1'].append(val_f1)

            # Print epoch statistics
            print(f'Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}')
            print(f'Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}')
            print(f'Val Precision: {val_precision:.4f}, Val Recall: {val_recall:.4f}, Val F1: {val_f1:.4f}')

            # Check if this is the best model
            if val_acc > best_val_acc:
                best_val_acc = val_acc
                best_val_loss = val_loss

                # Save the best model
                torch.save(model.state_dict(), f'{models_dir}/best_model_fold_{fold+1}.pt')

                # Reset patience counter
                patience_counter = 0

                # Plot confusion matrix for the best model
                cm = confusion_matrix(val_labels, val_preds)
                plt.figure(figsize=(10, 8))
                sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                           xticklabels=dataset.classes, yticklabels=dataset.classes)
                plt.xlabel('Predicted')
                plt.ylabel('True')
                plt.title(f'Confusion Matrix - Fold {fold+1}, Epoch {epoch+1} (No Augmentation)')
                plt.tight_layout()
                plt.savefig(f'{plots_dir}/confusion_matrix_fold_{fold+1}.png')
                plt.close()
            else:
                patience_counter += 1

            # Early stopping
            if patience_counter >= patience:
                print(f'Early stopping triggered at epoch {epoch+1}')
                break

        # Plot metrics for this fold
        plot_metrics(metrics_history, fold+1, save_dir=plots_dir)

        # Store metrics for later comparison
        fold_metrics = {
            'train_loss': metrics_history['train_loss'],
            'train_acc': metrics_history['train_acc'],
            'val_loss': metrics_history['val_loss'],
            'val_acc': metrics_history['val_acc'],
            'best_val_acc': best_val_acc,
            'best_val_loss': best_val_loss
        }
        all_folds_metrics.append(fold_metrics)

        # Store fold results
        fold_result = {
            'fold': fold+1,
            'best_val_acc': best_val_acc,
            'best_val_loss': best_val_loss,
            'best_val_precision': max(metrics_history['val_precision']),
            'best_val_recall': max(metrics_history['val_recall']),
            'best_val_f1': max(metrics_history['val_f1'])
        }
        all_results.append(fold_result)

        # Clear GPU memory
        torch.cuda.empty_cache()

    # Plot comparison across folds
    plot_fold_comparison(all_folds_metrics, save_dir=plots_dir)
    plot_average_metrics_across_epochs(all_folds_metrics, save_dir=plots_dir)

    # Print overall results
    print("\nResults across all folds (No Augmentation):")
    avg_acc = sum([res['best_val_acc'] for res in all_results]) / len(all_results)
    avg_loss = sum([res['best_val_loss'] for res in all_results]) / len(all_results)
    avg_precision = sum([res['best_val_precision'] for res in all_results]) / len(all_results)
    avg_recall = sum([res['best_val_recall'] for res in all_results]) / len(all_results)
    avg_f1 = sum([res['best_val_f1'] for res in all_results]) / len(all_results)

    print(f"Average Validation Accuracy: {avg_acc:.4f}")
    print(f"Average Validation Loss: {avg_loss:.4f}")
    print(f"Average Validation Precision: {avg_precision:.4f}")
    print(f"Average Validation Recall: {avg_recall:.4f}")
    print(f"Average Validation F1 Score: {avg_f1:.4f}")

    # Save detailed results
    results_df = pd.DataFrame(all_results)
    results_df.to_csv('./results_summary_no_aug.csv', index=False)

    # Test the best model
    test_dir = "/home/rifat/Dr.Rifat_sir_student_SUHA/FetalMRI_Dataset/"  # Update with your path
    if os.path.exists(test_dir):
        print("\nEvaluating on test set...")
        test_dataset = FetalMRIHybridDataset(test_dir, swin_processor, is_train=False)
        test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False)

        # Find best fold model
        best_fold = np.argmax([res['best_val_acc'] for res in all_results])
        best_model_path = f'{models_dir}/best_model_fold_{best_fold+1}.pt'

        # Load the best model
        best_model = HybridCNNSwin(num_classes=len(dataset.classes))
        best_model.load_state_dict(torch.load(best_model_path))
        best_model.to(device)

        # Evaluate on test set
        test_loss, test_acc, test_precision, test_recall, test_f1, test_preds, test_labels = evaluate_model(
            best_model, test_loader, criterion, device
        )

        print(f"Test Accuracy: {test_acc:.4f}")
        print(f"Test Loss: {test_loss:.4f}")
        print(f"Test Precision: {test_precision:.4f}")
        print(f"Test Recall: {test_recall:.4f}")
        print(f"Test F1 Score: {test_f1:.4f}")

        # Plot confusion matrix for test set
        cm = confusion_matrix(test_labels, test_preds)
        plt.figure(figsize=(10, 8))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                   xticklabels=dataset.classes, yticklabels=dataset.classes)
        plt.xlabel('Predicted')
        plt.ylabel('True')
        plt.title('Confusion Matrix - Test Set (No Augmentation)')
        plt.tight_layout()
        plt.savefig(f'{plots_dir}/confusion_matrix_test.png')
        plt.close()


def plot_class_distributions(dataset, save_dir='./plots'):
    """
    Plot class distributions in the dataset

    Args:
        dataset: The dataset to analyze
        save_dir: Directory to save plots
    """
    os.makedirs(save_dir, exist_ok=True)

    # Count samples per class
    class_counts = {}
    for label in dataset.labels:
        class_name = dataset.classes[label]
        class_counts[class_name] = class_counts.get(class_name, 0) + 1

    # Create bar plot
    plt.figure(figsize=(12, 6))
    plt.bar(class_counts.keys(), class_counts.values())
    plt.xlabel('Class')
    plt.ylabel('Number of Samples')
    plt.title('Class Distribution in Dataset')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.savefig(f'{save_dir}/class_distribution.png')
    plt.close()

def inference_on_image(model, image_path,  swin_processor, device, class_names):
    """
    Perform inference on a single image

    Args:
        model: Trained model
        image_path: Path to the image
        vit_processor: ViT image processor
        device: Device to use for inference
        class_names: List of class names

    Returns:
        predicted_class: Predicted class name
        confidence: Confidence score
    """
    # Load and preprocess the image
    image = Image.open(image_path).convert('RGB')

    # Process for ViT
    vit_processed =  swin_processor(images=image, return_tensors="pt")
    vit_pixels = vit_processed.pixel_values.squeeze().to(device)

    # Process for CNN
    cnn_transform = transforms.Compose([
        transforms.Resize(224),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    cnn_pixels = cnn_transform(image).to(device)

    # Add batch dimension
    vit_pixels = vit_pixels.unsqueeze(0)
    cnn_pixels = cnn_pixels.unsqueeze(0)

    # Set model to evaluation mode
    model.eval()

    # Perform inference
    with torch.no_grad():
        outputs = model(vit_pixels, cnn_pixels)
        probs = torch.nn.functional.softmax(outputs, dim=1)
        confidence, predicted = torch.max(probs, 1)

    # Get predicted class name
    predicted_class = class_names[predicted.item()]

    return predicted_class, confidence.item()

def analyze_gradcam(model, image_path, swin_processor, device, class_names, save_dir='./plots'):
    """
    Analyze model predictions using GradCAM

    Args:
        model: Trained model
        image_path: Path to the image
        vit_processor: ViT image processor
        device: Device to use for inference
        class_names: List of class names
        save_dir: Directory to save plots
    """
    os.makedirs(save_dir, exist_ok=True)

    # Load and preprocess the image
    image = Image.open(image_path).convert('RGB')
    image_np = np.array(image)

    # Process for CNN
    cnn_transform = transforms.Compose([
        transforms.Resize(224),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    cnn_pixels = cnn_transform(image).to(device)

    # Process for ViT
    vit_processed =  swin_processor(images=image, return_tensors="pt")
    vit_pixels = vit_processed.pixel_values.squeeze().to(device)

    # Add batch dimension
    vit_pixels = vit_pixels.unsqueeze(0)
    cnn_pixels = cnn_pixels.unsqueeze(0)

    # Register hooks for GradCAM
    gradients = []
    activations = []

    def save_gradient(grad):
        gradients.append(grad.cpu().detach())

    def forward_hook(module, input, output):
        activations.append(output.cpu().detach())

    # Register hook for last convolutional layer in CNN
    target_layer = model.cnn.features[-2]  # Last conv layer before ReLU
    hook_handle = target_layer.register_forward_hook(forward_hook)

    # Set model to evaluation mode
    model.eval()

    # Get prediction
    vit_pixels.requires_grad_()
    cnn_pixels.requires_grad_()

    outputs = model(vit_pixels, cnn_pixels)
    predicted_class = torch.argmax(outputs, dim=1).item()

    # Backward pass for GradCAM
    model.zero_grad()

    # Register hook for gradients
    activations[-1].register_hook(save_gradient)

    # Backward pass for the predicted class
    one_hot = torch.zeros_like(outputs)
    one_hot[0, predicted_class] = 1
    outputs.backward(gradient=one_hot)

    # Generate GradCAM
    gradients = gradients[0]
    activations = activations[0]

    # Remove hooks
    hook_handle.remove()

    # Calculate weights
    weights = torch.mean(gradients, dim=(2, 3))

    # Create weighted activation map
    cam = torch.zeros(activations.shape[2:], dtype=torch.float32)
    for i, w in enumerate(weights[0]):
        cam += w * activations[0, i]

    # Apply ReLU to CAM
    cam = np.maximum(cam.numpy(), 0)

    # Normalize CAM
    cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)

    # Resize CAM to match original image
    cam = cv2.resize(cam, (image_np.shape[1], image_np.shape[0]))

    # Convert CAM to heatmap
    heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
    heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)

    # Overlay heatmap on original image
    alpha = 0.4
    overlay = heatmap * alpha + image_np * (1 - alpha)
    overlay = overlay.astype(np.uint8)

    # Plot original image and overlay
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))
    ax1.imshow(image_np)
    ax1.set_title(f'Original Image\nPredicted: {class_names[predicted_class]}')
    ax1.axis('off')

    ax2.imshow(overlay)
    ax2.set_title('GradCAM Visualization')
    ax2.axis('off')

    plt.tight_layout()

    # Extract filename from path
    filename = os.path.basename(image_path).split('.')[0]
    plt.savefig(f'{save_dir}/gradcam_{filename}.png')
    plt.close()

    return class_names[predicted_class]

if __name__ == "__main__":
    # Set random seeds for reproducibility
    torch.manual_seed(42)
    np.random.seed(42)
    random.seed(42)

    # Run the main function
    main()